FROM ubuntu:latest 

EXPOSE 5000

RUN apt-get update && \
    apt-get install -y git python3 python3-pip python3-flask && \
    git clone https://github.com/AvshRLev/CS50x-Final-Project/ && \
    cd CS50x-Final-Project/ && \
    pip3 install -r requirements.txt 

WORKDIR /CS50x-Final-Project

CMD  flask run --host 0.0.0.0
